### ISSUE TITLE
Enable configmap

### ISSUE THREAD

**Issue by huang195** [fr8r/fr8r-ansible#100]
Allow user to access configmap within his namespace and enforce quota for it.

**Comment by huang195** [comment]
cc @mrsabath 
We will need to add configmap to the initial quota during tenant onboarding.

**Comment by MikeSpreitzer** [comment]
Issue moved to [fr8r/fr8r-proxy #12](https://github.com/fr8r/fr8r-proxy/issues/12) via [**ZenHub**](https://www.zenhub.com/)
