### ISSUE TITLE
Proxy plugins

### ISSUE THREAD

**Issue by Frugghi** [fr8r/fr8r-ansible#11]
My proposal for proxy plugins is [here](https://github.com/Frugghi/containercafe/tree/plugin).

Go doesn't allow dynamic linking of code yet, so the only solution I found is to use subprocesses and RPC.

### Pros:
- A subprocess can't crash the main process
- RPC allows the communication with code written in another language (but I haven't tested this possibility)
- Run a plugin without recompile the proxy

### Cons:
- Worst performances (but I don't think that RPC locally cost that much...)
- More complexity

## Example of plugin
I created only one type of plugin (`AuthPlugin`) and [`fileauth.go`](https://github.com/Frugghi/containercafe/blob/plugin/proxy/src/fileauth/fileauth.go) is an example of it. An auth plugin must implements the `AuthPlugin` interface and call `StartAuthPlugin` in its main:
```go
import (
	"auth"
	"plugin"
)

func main() {
    plugin.StartAuthPlugin(new(FileAuth))
}

func (FileAuth) GetAuth(TLS tls.ConnectionState) (auth.Creds) {
    // missing implementation
}

func (FileAuth) GetNamespace(space_id string) (string) {
    // missing implementation
}
```

## AuthPlugin interface
The `AuthPlugin` interface is:
```go
type AuthPlugin interface {
    GetAuth(TLS tls.ConnectionState) (auth.Creds)
    GetNamespace(space_id string) (string)
}
```
And the equivalent RPC interface is:
```go
func GetAuth(TLS tls.ConnectionState, creds *auth.Creds) error {}
func GetNamespace(space_id string, namespace *string) error {}
```
The RPC interface is hidden, so the plugin is unaware of using RPC. This is only a design choice to decouple the plugin from the underlying communication technology.

On the proxy-side I kept the same interface of the old `fileauth.go`:
```go
func Auth(r *http.Request) (creds auth.Creds) {}
func GetNamespace(space_id string) (namespace string) {}
```

## Environment variables
The plugin is loaded from the proxy looking at the value of the environment variable `auth_plugin_file`. So it's supported only one auth plugin at the time but should be easy to extend to support multiple plugins of the same type if required.

## Debugging the plugin
The plugin is started from the main process using the Go `exec.Command()` method and the output of the `log` package is redirected to the logger of the proxy.

## Architecture
The `plugin` package contains the plugin system files for the proxy and the custom plugins.

### Plugin.go
[`plugin.go`](https://github.com/Frugghi/containercafe/blob/plugin/proxy/src/plugin/plugin.go) contains a set of commons method used by all the plugins and hides the external library. It also defines a set of useful structs.

```go
// Keeps a reference to the external library Client and RPCClient
type Client struct {
    client *plugin.Client
    rpcClient *plugin.RPCClient
}

// Plugin do the RPC calls from proxy to the plugin
type Plugin struct {
    client *rpc.Client
}

// PluginImplementation invokes the plugin methods from RPC
type PluginImplementation struct {
    Impl interface{}
}

// Each plugin has an unique name and a version number
type PluginConfig struct {
    version uint
    name string
}

// Create a new Client - starts the plugin process (called from the proxy)
func NewClient(pluginPath string, pluginConfig PluginConfig) (*Client) {}

// Returns a Plugin that implements the required interface (called from the proxy)
func (Client) Dispense(pluginName string) (*Plugin) {}

// Start a plugin that accepts RPC calls (called from the plugin)
func StartPlugin(config PluginConfig, impl interface{}) {}
```

### Authplugin.go
[`authplugin.go`](https://github.com/Frugghi/containercafe/blob/plugin/proxy/src/plugin/authplugin.go) defines what is a `AuthPlugin` and contains a set of methods that hides the RPC calls from the proxy and the plugins.

#### Proxy side
```go
// Returns a Plugin that can call RPC methods to a plugin that implements the AuthPlugin interface
func GetAuthPlugin() (*Plugin) {}

// Do the GetAuth RPC call
func (*Plugin) Auth(r *http.Request) (auth.Creds) {}

// Do the GetNamespace RPC call
func (*Plugin) GetNamespace(space_id string) (string) {}
```

#### Plugin side
```go
// Register the object that implements AuthPlugin so it can be called from the RPC methods
func StartAuthPlugin(implementation AuthPlugin) {}

// This is the RPC method that invokes GetAuth on the implementation of AuthPlugin interface
func (PluginImplementation) GetAuth(TLS tls.ConnectionState, creds *auth.Creds) error {}

// This is the RPC method that invokes GetNamespace on the implementation of AuthPlugin interface
func (PluginImplementation) GetNamespace(space_id string, namespace *string) error {}
```

## Issues
- using RPC it's not possible to add headers to the `http.Request`, I moved that part in the proxy but I don't know if it's a specific case of `FileAuth`
- I based my `AuthPlugin` interface on my only example (`FileAuth`) and probably should be more general
- I've added one more dependency to the project but it could be possible to this only with golang packages

**Comment by MikeSpreitzer** [comment]
Issue moved to [fr8r/fr8r-proxy #9](https://github.com/fr8r/fr8r-proxy/issues/9) via [**ZenHub**](https://www.zenhub.com/)
