### ISSUE TITLE
New tenant onboarding needs quota and limitrange to be setup

### ISSUE THREAD

**Issue by huang195** [fr8r/fr8r-ansible#114]
@mrsabath per our discussion on slack

**Comment by huang195** [comment]
Confirmed that we already have quota and limitrange set up during new tenant onboarding. However a few things need to be dynamic.

On the quota, we should give paid tenant vs. free tenant different amount of quota. For the paid tenant, if he is willing to pay for more, we should give him more quota. We can talk about dynamically changing quota for tenants later, as that is a separate issue. For now, I'm only talking about during onboarding time, quota for different tenants could be set differently.

For the limitrange, the `max` value for containers and pods should vary depending on the deployment environment. Assuming having a homogeneous cluster, each node has 16 cores, we should set the `max` cpu value to be a bit under 16, e.g., 14. In another homogeneous cluster with each node having only 4 cores, the `max` cpu value could be 2, just as an example.

**Comment by mrsabath** [comment]
Can I assume a single value for the entire deployment? Or we need to have a different limits per tenants?

**Comment by huang195** [comment]
For limitrange, we can assume for now, it's one for the entire shard.
For quota, we should expect different users would have different quota.

**Comment by mrsabath** [comment]
@huang195 I will added the tenant level quotas and limits using this issue, but for the shard level, after consulting with @MikeSpreitzer we decided to do this right, using the key/value service (issues #145 and #144 )

**Comment by huang195** [comment]
SGTM
