### ISSUE TITLE
docker commands require superuser privileges to execute (tiny example)

### ISSUE THREAD

**Issue by srikumar003** [fr8r/fr8r-ansible#62]

**Comment by srikumar003** [comment]
I followed the steps to run the tiny example until  I ssh-ed into the shard and executed `docker ps`. This produced the error message that Docker daemon does not seem to be running on the machine. 
But `sudo docker ps` worked. 

Either the documentation of the tiny example has to be modified or else the Vagrantfiles have to be modified so that user `vagrant` can execute docker commands. I have done the latter and can make a pull request if this is the chosen path.

**Comment by MikeSpreitzer** [comment]
Lin has stopped complaining about this, so I suppose the fix is OK.
