### ISSUE TITLE
Need to document how to use proxy running on dedicated Proxy VM

### ISSUE THREAD

**Issue by mrsabath** [fr8r/fr8r-ansible#65]
We need to expend the tiny examples with steps to create tenants and setup environments for proxy running on VM

**Comment by MikeSpreitzer** [comment]
Is there any documentation for how to use the proxy in general?

**Comment by MikeSpreitzer** [comment]
I found some general doc at https://github.com/containercafe/containercafe/blob/master/proxy/README.md, but it is not referenced from the tiny example doc nor any doc mentioned by that.  And it assumes the machine running the proxy container has `kubectl` installed, which is not true of the tiny example's proxy VM.

**Comment by mrsabath** [comment]
@MikeSpreitzer, the proxy documentation is linked form https://github.com/containercafe/containercafe/blob/master/examples/tiny-example.md#optionally-deploy-the-openradiant-api-proxy section. It shows the steps to get proxy running on local docker host. This task is about extending the proxy steps with proxy running on api-proxy VM

**Comment by MikeSpreitzer** [comment]
My point is that we need documentation for how to use the proxy in general.  That needs to be the first priority.  I found some such, and have been testing it, and finding issues.
The tiny example doc should reference the general doc, for this subject as well as others.
